# Generated by Django 3.0.6 on 2020-11-15 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('desc', models.TextField(null=True)),
                ('image', models.ImageField(upload_to='pics')),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
