# Generated by Django 3.1.6 on 2021-07-04 05:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201115_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('desc', models.TextField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='pics')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo')),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
